import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import WalletContextProvider from "@/components/WalletContextProvider";
import { Toaster } from 'sonner';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const ApiKey = process.env.ALCHEMY_API_KEY;
  return (
    <html lang="en">
      <body className={inter.className}>
        <WalletContextProvider ApiKey={ApiKey!}>
          <Header />
          {children}
          <Toaster richColors={true} position="bottom-right"/>
        </WalletContextProvider>
      </body>
    </html>
  );
}
